name: tests
on: [push, pull_request]
jobs:
  headless:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim: [v0.10.4, stable]
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim }}
      - run: nvim --headless -u NONE -l tests/run.lua
      - run: nvim --headless -u NONE -l tests/operations.lua
